### ISSUE TITLE
Add to Main Site

### ISSUE THREAD

**Issue by mAzurkovic** [1010Robotics/Resources#2]
Just a suggestion to add the resources link to the main Ten Ton site.

**Comment by mchugani** [comment]
You bring up an interesting point...now we have 2 web sites...this one on GitHub, and the Ten Ton website on Wix. Josh also has a whole bunch of resources on Google Docs.  Lets discuss next time we are in class and see how to handle all of these. Thanks for bringing this up! @Big-T-Bot-Boss @mAzurkovic @justjoshwhite

**Comment by mchugani** [comment]
Discussed with Josh and Mr. Ablett. We will be using links on GitHub to point users to the other places where 1010Robotics materials/information exists.
