### ISSUE TITLE
FRC Programming Resources

### ISSUE THREAD

**Issue by mAzurkovic** [1010Robotics/Resources#5]
#### Mainly resources related to Java for FRC...
This year during the FRC season, I accumulated some FRC Java related resources that were helpful to me when programming the FRC bot. Should they be put in the `readme.md` file, or a separate file named something like `frc_resources.md` ?

**Comment by mchugani** [comment]
Yes, it would be great to get the list of resources related to FRC Java! 

Can you please do the following:

1. Fork the **1010Robotics/Resources** repo to your account
2. Edit the **Readme.md** file to include the list of resources.
3. Create a **Pull Request** so I can pull the changes to the **1010Robotics** account.

Thanks!

**Comment by mchugani** [comment]
Completed with pull request and merged into README.md file.
