### ISSUE TITLE
Stickers Files- where to put?

### ISSUE THREAD

**Issue by jwhite2a** [1010Robotics/Resources#9]
[link to google drive folder of sticker files](https://drive.google.com/open?id=0B2yYAJOLKOCDcVFsTHl1amFWVEk). It can be viewed by anyone with the link. 

The link includes the .jpg and .pngs of most sticker designs. 
It also includes the PowerPoint used to design the stickers, and the word documents used to print the stickers on sticker paper. 

What is the best way to put these file on github? I think posting the drive link is best. 

**Where should this link go?**

**Comment by mchugani** [comment]
It is a resource (folder with stickers) ...so we can put it under **Resources**. You can create a file **Useful Materials.md**, and put the link to the folder in this file. Then edit **README.md** in the **Resources** folder, and add a link to **Useful Materials.md** (after the **TUTORIALS** section).
